In [1]:
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import clear_output
import time

In [2]:
G=(lambda x,y,z: 6*x-2*np.cos(y*z)-1, \
   lambda x,y,z: 9*y+np.sqrt(x**2+np.sin(z)+1.06)+0.9, \
   lambda x,y,z: 60*z+3*np.exp(-x*y)+10*np.pi-3)

In [3]:
def GetVectorF(G,r,h=1e-6):
    dim = len(G)
    v = np.zeros(dim)
    
    for i in range(dim):
        v[i] = G[i](r[0],r[1],r[2])
        
    return v

In [4]:
def GetJacobian(G,r,h=1e-6):
    
    dim = len(G)
    
    J = np.zeros((dim,dim))
    
    for i in range(dim):
        J[i,0] = (  G[i](r[0]+h,r[1],r[2]) - G[i](r[0]-h,r[1],r[2]) )/(2*h)
        J[i,1] = (  G[i](r[0],r[1]+h,r[2]) - G[i](r[0],r[1]-h,r[2]) )/(2*h)
        J[i,2] = (  G[i](r[0],r[1],r[2]+h) - G[i](r[0],r[1],r[2]-h) )/(2*h)
        
    return J.T

In [5]:
def NewtonRaphson(G,r,error=1e-10):
    
    it = 0
    d = 1
    Vector_d = np.array([])
    
    while d > error:
        
        it += 1
        
        rc = r
        
        F = GetVectorF(G,r)
        J = GetJacobian(G,r)
        InvJ = np.linalg.inv(J)
        
        r = rc - np.dot( InvJ, F )
        
        diff = r - rc
        print(diff)
        
        d = np.linalg.norm(diff)
        
        Vector_d = np.append( Vector_d , d )
        
    return r,it,Vector_d

In [6]:
r,it,distancias = NewtonRaphson(G,[1,2,3])
print(r,it)

[-0.70110649 -2.55368154 -3.50762578]
[ 0.17460598  0.36544215 -0.02734569]
[ 0.0248364  -0.00806853  0.00679288]
[ 0.00024986 -0.00343866 -0.00053104]
[-4.36240492e-04  7.86806494e-05 -1.26026817e-04]
[-1.27262142e-05  6.34249709e-05  7.39716704e-06]
[ 7.67930096e-06 -2.71948285e-07  2.41077135e-06]
[ 3.69080931e-07 -1.15233290e-06 -9.01935344e-08]
[-1.32236340e-07 -1.59248992e-08 -4.52429205e-08]
[-9.06878206e-09  2.05575029e-08  8.13150991e-10]
[2.22809132e-09 6.59963750e-10 8.33150215e-10]
[ 2.04359418e-10 -3.59944768e-10  3.61710661e-13]
[-3.66090491e-11 -1.84500470e-11 -1.50650603e-11]
[ 0.49814468 -0.1996059  -0.52882598] 13


In [7]:
def GetMetric(G,r):
    v = GetVectorF(G,r)
    return 0.5*np.linalg.norm(v)**2

In [8]:

GetMetric(G,[1,0,0])

500.7069630629646

In [9]:
def GetFig(F,R,it):
    
    fig = plt.figure(figsize=(8,4))
    
    labels = ['X','Y','Z']
    
    ax = fig.add_subplot(1,2,1)
    ax1 = fig.add_subplot(1,2,2)

    ax.set_title('Metric: %.20f' %(F[it]))

    ax.plot(F[:it])
    ax.set_xlabel('%.0f' %(it))
    ax.set_yscale('log')
    ax1.plot(R[:it],label=labels)
    ax1.set_xlabel('%.0f' %(it))
    ax1.legend(loc=0)
    
    plt.show()

In [10]:
def GetSolve(G,r,lr=1e-3,epochs=int(1e5),error=1e-7):
    
    d = 1
    it = 0
    Vector_F = np.array([])
    
    R_vector = np.array(r)
    
    while d > error and it < epochs:
        
        CurrentF = GetMetric(G,r)
        
        J = GetJacobian(G,r)
        
        GVector = GetVectorF(G,r)
        
        #Machine Learning
        r -= lr*np.dot(J,GVector) 
        
        R_vector = np.vstack((R_vector,r))
        
        NewF = GetMetric(G,r)
        
        
        Vector_F = np.append(Vector_F,NewF)
        
        d = np.abs( CurrentF - NewF )/NewF
        
        
        if it%500 == 0:
            
            #print(it,d)
            clear_output(wait=True)
            time.sleep(0.01)
            
        it += 1
        
    if d < error:
        print(' Entrenamiento completo ', d, 'iteraciones', it)
        
    if it == epochs:
        print(' Entrenamiento no completado ')
        
    return r,it,Vector_F,R_vector

In [11]:
xsol,it,F,R = GetSolve(G,[0,0,0],lr=1e-4)

 Entrenamiento completo  0.0 iteraciones 8536


In [12]:
xsol

array([ 0.49814468, -0.1996059 , -0.52882598])

In [ ]:
#coinciden con los valores del libro