In [1]:
import numpy as np

A = np.array([[1,0,0],[5,1,0],[-2,3,1]])
B = np.array([[4,-2,1],[0,3,7],[0,0,2]])

def multima(a,b):
  m_one = np.size(a, 0)
  n_one = np.size(a, 1)
  m_two = np.size(b, 0)
  n_two = np.size(b, 1)
  k1 = n_one
  if n_one == m_two:
    c = np.zeros([m_one,n_two])
    for i in range(m_one):
      for j in range(n_two):
        entrada = 0
        for k in range(k1):
          #print(k)
          entrada = entrada + (a[i][k] * b[k][j])
        c[i][j] = entrada
    return c
  else:
    return "paila"

print(multima(A,B))        








[[ 4. -2.  1.]
 [20. -7. 12.]
 [-8. 13. 21.]]
